// GENERATED BY AMBORAS — do not edit manually
// Generated: 2026-05-07T22:02:27.119Z
// Class A plugins: klaviyo, cj-dropshipping
// Types are inlined — this file has no external imports so it builds even before slot infra is added.
type PluginRegistry = Record<string, Array<{ id: string; src?: string; strategy?: string; when?: string; Component?: unknown; propsFromConfig?: Record<string,string>; propsFromContext?: string[] }>>
import { KlaviyoProvider as klaviyo_KlaviyoProvider } from "@amboras-dev/klaviyo"
import { KlaviyoIdentifyOnLogin as klaviyo_KlaviyoIdentifyOnLogin } from "@amboras-dev/klaviyo"

export const PLUGIN_REGISTRY: PluginRegistry = {
  head: [],
  bodyEnd: [],
  rootProviders: [{ id: 'klaviyo', Component: klaviyo_KlaviyoProvider, propsFromConfig: {"publicKey":"publicKey"} }],
  homeHero: [],
  homeBelowFeatured: [],
  pdpAfterTitle: [],
  pdpBeforePrice: [],
  pdpBelowAddToCart: [],
  pdpTrustSignals: [],
  pdpAfterDescription: [],
  pdpTab: [],
  pdpAnalytics: [],
  collectionAboveGrid: [],
  collectionCard: [],
  collectionBelowGrid: [],
  cartDrawerFooter: [],
  cartUpdate: [],
  checkoutOrderSummary: [],
  checkoutStart: [],
  checkoutComplete: [],
  searchAboveResults: [],
  accountOverview: [],
  account: [{ id: 'klaviyo', Component: klaviyo_KlaviyoIdentifyOnLogin, propsFromContext: ["email","customerId"] }],
  authSignup: [],
}