// GENERATED BY AMBORAS — do not edit manually
// Generated: 2026-05-17T08:15:24.707Z
// Class A plugins: klaviyo, cj-dropshipping

import type { PluginRegistry } from '../../types/plugins'
import { KlaviyoProvider as klaviyo_KlaviyoProvider } from "@amboras-dev/klaviyo"
import { KlaviyoIdentifyOnLogin as klaviyo_KlaviyoIdentifyOnLogin } from "@amboras-dev/klaviyo"

export const PLUGIN_REGISTRY: PluginRegistry = {
  head: [],
  bodyEnd: [],
  rootProviders: [{ id: 'klaviyo', Component: klaviyo_KlaviyoProvider, propsFromConfig: {"publicKey":"publicKey"} }],
  homeHero: [],
  homeBelowFeatured: [],
  pdpAfterTitle: [],
  pdpBeforePrice: [],
  pdpBelowAddToCart: [],
  pdpTrustSignals: [],
  pdpAfterDescription: [],
  pdpTab: [],
  pdpAnalytics: [],
  collectionAboveGrid: [],
  collectionCard: [],
  collectionBelowGrid: [],
  cartDrawerFooter: [],
  cartUpdate: [],
  checkoutOrderSummary: [],
  checkoutStart: [],
  checkoutComplete: [],
  searchAboveResults: [],
  accountOverview: [],
  account: [{ id: 'klaviyo', Component: klaviyo_KlaviyoIdentifyOnLogin, propsFromContext: ["email","customerId"] }],
  authSignup: [],
}